# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-23 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to='online_shop_dashboard/images'),
        ),
    ]
