# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-23 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_dashboard', '0002_auto_20191123_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
