# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('online_shop_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('address_2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('buy_it_later', models.ManyToManyField(related_name='interested_users', to='online_shop_dashboard.Product')),
                ('shopping_cart', models.ManyToManyField(related_name='buying_users', to='online_shop_dashboard.Product')),
            ],
        ),
    ]
